apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app


spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  
  
  
  template:
    metadata:
      name: my-web-app
      labels:
        app: my-web-app
    spec:
      containers:
        - image: nouran222002/nginx-nouran
          name: nginx-app
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 80