apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec:
  containers:
    - image: nouran222002/nginx-nouran
      name: nginx-app
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80